// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqzwpojjvlntfkdtdslz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxendwb2pqdmxudGZrZHRkc2x6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MjE2MzYsImV4cCI6MjA1NTE5NzYzNn0.IGosl0mA3UY5DgDXPoyrT2Iqgr2ZpQQWD94jFWHnjv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);